// Manually update these tables if new topics are needed. Make sure to also update post.py as well.
const TagsIdToName: Map<number, string> = new Map<number, string>();
TagsIdToName.set(0, "oop");
TagsIdToName.set(1, "dev-tools");
TagsIdToName.set(2, "systems-design");
TagsIdToName.set(3, "data-structures-algorithms");
TagsIdToName.set(4, "programming-languages");
TagsIdToName.set(5, "advanced-topics");
TagsIdToName.set(6, "back-end");
TagsIdToName.set(7, "front-end");
TagsIdToName.set(8, "frameworks");
TagsIdToName.set(9, "deployment");
TagsIdToName.set(10, "interpersonal");
TagsIdToName.set(11, "interviews");
TagsIdToName.set(12, "testing");
TagsIdToName.set(13, "cloud-infrastructure");
TagsIdToName.set(14, "quality-assurance");
TagsIdToName.set(15, "career");
TagsIdToName.set(16, "miscellaneous");

const TagsNametoId: Map<string, number> = new Map<string, number>();
TagsNametoId.set("oop", 0);
TagsNametoId.set("dev-tools", 1);
TagsNametoId.set("systems-design", 2);
TagsNametoId.set("data-structures-algorithms", 3);
TagsNametoId.set("programming-languages", 4);
TagsNametoId.set("advanced-topics", 5);
TagsNametoId.set("back-end", 6);
TagsNametoId.set("front-end", 7);
TagsNametoId.set("frameworks", 8);
TagsNametoId.set("deployment", 9);
TagsNametoId.set("interpersonal", 10);
TagsNametoId.set("interviews", 11);
TagsNametoId.set("testing", 12);
TagsNametoId.set("cloud-infrastructure", 13);
TagsNametoId.set("quality-assurance", 14);
TagsNametoId.set("career", 15);
TagsNametoId.set("miscellaneous", 16);

export { TagsIdToName, TagsNametoId };
